test: test.cpp simplekvstore.h record.h recordoffset.h simplekvindex.h task.h error.h queue.h thread.h datanode.h kvlogiclayer.h kvnetworklayer.h basetcpsocket.h epoll.h bug.h cache.h linkedlist.h
	g++ -o test test.cpp -lpthread -ggdb
